import os

TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', NONE)
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', NONE)
TWILIO_PHONE_NUMBER = os.environ.get('TWILIO_PHONE_NUMBER', NONE)
AGENT_PHONE_NUMBER = os.environ.get('AGENT_PHONE_NUMBER', NONE)
